### PR TITLE
reformat copyright

### PR DESCRIPTION
**Pull request by PaulRomerolegal**
for clarity

### CODE REVIEW

**Comment by miguelfreitas** [comment]
That's funny. Why do these fake users like @PaulRomerolegal and @jessicalinux suddenly decided to start contributing cosmetic changes to twister?

**Comment by slr** [comment]
> Why

why not? just ask them to not open pull requests until all those changes are done.

**Comment by miguelfreitas** [comment]
I don't know. They seem to be trying to build a history of "good contributors". What for? I have no idea.

**Comment by pete** [comment]
Maybe to sell the accounts later? I can imagine there's a market for accounts that have had pull requests accepted into interesting repos.  (Now that I think about it, I'd be surprised if there wasn't.)  Change the username and photo and suddenly you have an account that, if you don't look too closely, has contributed to some interesting projects.

I see people with accounts that have early histories like these used by offshore devs.

**Comment by PaulRomerolegal** [comment]
I'm only helping. I can't see any disadvantages of "_contributing cosmetic changes to twister_"! Would you mind clarifying what your problem is?

**Comment by PaulRomerolegal** [comment]
@pete Jeez. This isn't a conspiracy by the Peruvian government to get some _trusted_ accounts for their sneaky spies.
...
...
...
...
[Algerian spies laugh in background]

**Comment by PaulRomerolegal** [comment]
@miguelfreitas was this really so unhelpful a PR? Looks pretty sensible/merge-able to me. 😊

**Comment by PaulRomerolegal** [comment]
In summary, I'm trying to help.

**Comment by pete** [comment]
@PaulRomerolegal The "conspiracy" I suggested was much more mundane, and is more "sending some kid through a code bootcamp and then setting him up with a respectable-looking github account to pad the respectability of your high-turnover discount dev shop" than "spies".

There's more money in cut-rate dev shops than there is in a World of Warcraft account, so it'd be more surprising if there were no instances of the Github equivalent of "gold-farming"  It's general speculation, it may not apply to you.

**Comment by myleneb** [comment]
> I don't know. They seem to be trying to build a history of "good contributors". What for? I have no idea.
@miguelfreitas I've already seen that behavior on other repositories.

**Comment by PaulRomerolegal** [comment]
I give up.

**Pull request closed without merging**
