### PR TITLE
post editing

### PR DESCRIPTION
**Pull request by erqan**
adding edit functionality with `editpost` method.. and it changes `createSignedUserpost` function...

    editpost <username> <k> <edit_k> [msg='']
    Edit post
    if msg is omited, post <edit_k> will be dropped

* edit post to **replace**
```
    {
        "sig_userpost" : "20ff1f6c1c8bced2c01ecd6321cd96144998521bbb4cc76c694ea544b82ff297f60e1c13cb877c8a91b47476eccda853b269170200882773d86a4f18a921efbb56",
        "userpost" : {
            "edit" : {
                "sig_userpost" : "20fba7205ecf296a09c29cd903a0b9e9507ecdc5cedb97a589269ed88bebf6782700902021d7f668d32ab244d487c42416faeb7fea839be52bf0e9d127d996f773",
                "userpost" : {
                    "height" : 97897,
                    "k" : 304,
                    "lastk" : 303,
                    "msg" : "yeniden #304",
                    "n" : "erqan",
                    "orig_time" : 1432742483,
                    "time" : 1438474653
                }
            },
            "height" : 97897,
            "k" : 325,
            "n" : "erqan",
            "time" : 1438474653
        }
    }
```
* edit post to **drop**
```
    {
        "sig_userpost" : "1fe91eb3ebcc644d70de1136b86a24a9dc0237e517a8c4d2f68e73af926358bce7aef54d779741dc976419ced26aa6070d40d5f388293f8b020f2dd3a4140197ad",
        "userpost" : {
            "edit" : {
                "sig_userpost" : "1f57d799e1fd0e3f3e310bac0e3349bb8e575fb53639e36a6b500c9bc8a9529bd82574c5384d13123161aea0a51582b244cc9a45e0a3d07a033314f1caf5c4c207",
                "userpost" : {
                    "drpd" : {
                        "time" : 1432742452
                    },
                    "height" : 97896,
                    "k" : 303,
                    "n" : "erqan",
                    "time" : 1438474592
                }
            },
            "height" : 97896,
            "k" : 324,
            "n" : "erqan",
            "time" : 1438474592
        }
    }
```
* dropped post in own storage:
```
    {
        "sig_userpost" : "1f80ec483e4b5d0da059b5f740046576885d9ac2efbb70b531d639a40b29a3af149cd6f10ae8100b01f8eb24384363464b7289ba55204a2f10400d19842e56956f",
        "time" : 1432742452,
        "userpost" : {
            "drpd" : {
                "height" : 88423,
                "k" : 303,
                "lastk" : 300,
                "msg" : "#deneme #k302",
                "n" : "erqan",
                "time" : 1432742452
            },
            "height" : 97896,
            "k" : 303,
            "n" : "erqan",
            "sig_drpd" : "20de822f2c08c4b8edfe223ebe0437ace00a846713599e59928312d39d75075eb8a51dd25774a9213291480a170c30debb237f582a3f2687bc08ca9b4919c4785e",
            "time" : 1438474592
        }
    }
```
* dropped post for other users:
```
    {
        "sig_userpost" : "1f57d799e1fd0e3f3e310bac0e3349bb8e575fb53639e36a6b500c9bc8a9529bd82574c5384d13123161aea0a51582b244cc9a45e0a3d07a033314f1caf5c4c207",
        "userpost" : {
            "drpd" : {
                "time" : 1432742452
            },
            "height" : 97896,
            "k" : 303,
            "n" : "erqan",
            "time" : 1438474592
        }
    }
```

### CODE REVIEW

**Comment by miguelfreitas** [comment]
looks very clever! i'm still digesting it...

how tested is this?

**Comment by erqan** [comment]
my test user sent some edit/drop messages and its followers watched out
how those are affect their storage from different instances/machines..

05-08-2015 14:27 tarihinde miguelfreitas yazdı:

**Comment by black-puppydog** [comment]
I had floated an idea for post editing myself at some point, informally over twister itself.
So I am not opposed to the idea itself but I want to make sure we don't mess it up.
So I have some questions about the semantics of all of this:

1. When a user drops a post, it will be dropped from the node they control (if any) and that node is expected to not distribute this post any further, correct? Since we cannot control other nodes the post will likely never be dropped from the entire network and it is obviously impossible to force this to happen. This needs to be communicated to the user *very clearly* to avoid some false sense of security.  Preferably on *every* delete, not just once in the "Terms and Conditions".

2. Editing posts will do something similar as deleting it but replacing the content instead of outright dropping it, correct? Again the question is how this will propagate through the network.
But this time it is (IMHO) more important that it does actually spread, since the user wants their followers to see the new version.
Now, don't get me wrong I am not criticizing what you wrote, in fact I am more asking *what* you did. :)
Specifically, if I edit or drop a post, how does my node get others to pull the new version of the entry's json object? Or do we (so far) rely on this information gradually spreading? Or does twisterd already have some piece/post management where it periodically checks old entries it already has locally?

My initial idea for post editing had been to introduce a "delta" post that references the old one and stores the new content. A deletion would then either correspond to storing an empty `msg` or a special marker in the delta post.
The good thing about this (though I never developed on it)( was that the information would naturally spread over the existing DHT/Torrent channels.
A node that receives a delta post would then be able to link it to the original post and previous edits, but would also be able to do the inverse.

Another point I find interesting about the whole topic: how would this be presented on the client side?
Because while *technically* twister would still be censorship resistant with this (a node cannot be forced to drop posts after all) if the user never sees that there *was* a post, or doesn't get an indication that the content has changed, this is severely weakened.
Personally, if I had to choose between being able to edit post and having twister really censorship resistant, I would choose the latter.
Luckily, I think we can have both if we do it right.

**Comment by thedod** [comment]
I admit I haven't looked at the code, but this talk about telling nodes not to propagate makes me shudder. The strength of twister is in bein sensorship proof. If I can willingly delete a typo, a judge (or a mobster) can force me to do be willing :wink:

OTOH, I understand the need to retract typos and lies you no longer believe. Banking systems have a similar problem. They're not allowed to delete anything, yet they have to deal with errors.

IMHO, what we need is a revision control system. You can edit a new version of a twist, and that includes a "non-twist": deleting it. This can be implemented as a fast [and sparse] lookup table mapping `[user,k]` to a list of later revisions.

Clients can have a link to previous revisions when presenting such a twist, and deleted twist can be presented as only the "view history" link :wink:

**Comment by Erkan-Yilmaz** [comment]
@thedod @black-puppydog
"The strength of twister is in being censorship-proof." +1
"IMHO, what we need is a revision control system." +1

**Comment by majestrate** [comment]
Sometimes it is necessary to remove your own posts but demanding others to remove them is a bit much, A comment revision system would be better sure but the ability to locally nuke a post would be great too.

**Comment by dryabov** [comment]
There was a discussion about edit/delete posts a year ago (not sure where it was, in twister or in this group), and the best solution is to keep original message and just create new message of special "overwrite" type. The html client should replace old message text by new one, but allow to look at the previous text (full history of editing). 06.08.2015, 15:03, "The Dod" <notifications@github.com>:I admit I haven't looked at the code, but this talk about telling nodes not to propagate makes me shudder. The strength of twister is in bein sensorship proof. If I can willingly delete a typo, a judge (or a mobster) can force me to do be willing OTOH, I understand the need to retract typos and lies you no longer believe. Banking systems have a similar problem. They're not allowed to delete anything, yet they have to deal with errors.IMHO, what we need is a revision control system. You can edit a new version of a twist, and that includes a "non-twist": deleting it. This can be implemented as a fast [and sparse] lookup table mapping [user,k] to a list of later revisions.Clients can have a link to previous revisions when presenting such a twist, and deleted twist can be presented as only the "view history" link —Reply to this email directly or view it on GitHub.  -------Best regards,Denis Ryabov

**Comment by black-puppydog** [comment]
Hah, found my old post:
https://twistnik.com/@black_puppydog/301

**Comment by slr** [comment]
> If I can willingly delete a typo, a judge (or a mobster) can force me to be willing to delete other things

but you can delete whole database of your posts from your machine, don't you? and you may ask all the people to search and delete your posts on their machines. it's just a mechanism to do it automatically. let's add some flags to allow or deny such requests to let people be able to choose.

generally, I don't like at all censorship of governments or corporations of course but I'm also want to decide what to recieve from others and store and retransmit to others further. and I suppose nobody has right to dictate me what I should to store or retransmit for fighting against censorship because it's obviously kind of that evil of part of which censorship is it. in your life you should be free to talk and to *not* talk about anything you want, right?

**Comment by Erkan-Yilmaz** [comment]
How are RTs (retwists) of a "changed (1) twist" handled in above scenarios?

If I have retwisted in the past the original version, I may perhaps not agree that my RT changes...

(1) change being: edited, deleted

**Comment by dryabov** [comment]
@Erkan-Yilmaz RT-type entry includes original text you retwisted, so it shouldn't be changed anyway.

**Comment by erqan** [comment]
proposed method is simply sending an *edit post* that encapsulate *new content*. if a twisterd instance receive that post, it will replace orijinal piece with that **encapsulated content**. 

to drop a post, it will be replaced with an `drpd` object and will be flaged as `DROPPED`. `DROPPED` posts won't be displayed and shared any more, all requests will be rejected. Own drpd objects will continue to __store orijinal post__, the others won't...

* if user A sends an `edit` post, its followers<sup>(*)</sup> will immediately replace the related piece.
* if user B<sup>(*)</sup> follows A after that post was sent, B can get _old_ post.. but at the end it will also receive the `edit` post, and B will replace the post too.
* if user C retwists or adds to fav or similar the original post, it won't be changed...
* replacing all copies is impossible (allways someones have the original one)
* there are also some services that cache the posts, i think they won't be update their db..
* something like `revisions mechanism` sounds good, but if a user want to edit/delete, we should respect..

(*) supposed that they use common version

**Comment by thedod** [comment]
Good point by @Erkan-Yilmaz:

> How are RTs (retwists) of a "changed (1) twist" handled in above scenarios?

It's important (from a "forensic" point of view) that if `@alice/5` was RTed by `@bob`, and later replaced by `@alice/23` (perhaps meaning the opposite now, e.g. if the word "not" was added or removed), that we'd know *which* twist was RTed. `@alice/5` is still "out there" (and I oppose ideas like @slr's to enable a request to **destroy forensics**, because that discriminates in favor of those who *don't* follow protocol and *intentionally* keep a copy in their "extortion potential" db).

An outdated twist should be displayed with a distinvtive [e.g. background color] "outdated" look (it would also have a "future" button, similar to the "history" one, just like a browser may display/enable "back"/"forward" buttons when relevant).

It's like the difference between a git *branch* (luckily, in twister's case, there's only "`master`" :wink:), and a single *commit* (the `HEAD` of that branch). Normally when I say `README.md` There's an implied "at `HEAD`" in there, but if we're bickering on "why did you edit my text?" context requires being commit-specific. **RT is a revision-specific relation**: when I expand I may see an "outdated" twist, and when I see the RTs of a later revision, it would not appear there (unless a client decides to have a *separate* count/list of "ghost RTs" of previous revisions).

**Comment by myleneb** [comment]
From a non-technical point of view: I don't like this idea and think it represents a serious issue for freedom of speech on twister.  I wish this could be fix so that post editing/removing would really be impossible.

**Comment by talexand** [comment]
Twister is ultimately a public forum, so it's definitely not a privacy issue in and of itself.

If you want to undo something you expressed on Twister, you can always apologize.

On a related note, can I bog down the network by continually re-editing all my posts (and making new ones) with this revised protocol? A naive analysis seems to say that I could create a quadratically increasing number of post updates this way as opposed to a linear one.

**Comment by erqan** [comment]
* RT isn't just a pointer, it copies the post to user swarm. so it will remain persist what you retwisted.

* this method won't block any one, won't filter any content.. this isn't about censorship, this is about the right of giving up. no one except you will be able to edit/drop the post...

> but, gov't may force you to delete some content..
 
sorry, but that's ridiculous... yes, they may sue you, but lack of `edit` function won't help you.. they won't be able to block *twister* or force the other users to forget, ignore what you write, so they will want to **block** you in any case..

**Comment by slr** [comment]
>> but, gov't may force you to delete some content..

> sorry, but that's ridiculous... yes, they may sue you, but lack of edit function won't help you.. they won't be able to block twister or force the other users to forget, ignore what you write, so they will want to block you in any case..

a word.

**Comment by black-puppydog** [comment]
Editing the twist objects in-place results in all kinds of UI semantics issues as @thedod  and @erqan described very well.
I was positive about this feature in the beginning, because I thought that the UI problems could be solved in a way that does not facilitate "cencorship" through the back-door. But now I am not so sure anymore.

In the end, if a user wants to edit or delete something, we should not give them the impression that they can when that is just not the case.
And quite frankly, trying to describe to a non-technical person what a revision system does (even if we didn't call it that) and the finer details of when and where retwists and answers are referenced (if we even could agree on some strategy) will be much more difficult than just being honest with them and telling them "There is no delete button".

And I disagree with @slr and @erqan about the censorship.
Outright censorship may not be possible with this because there might be people keeping all versions. But "drowning out" messages if far more useful anyway.
If by default the client only displays the latest revision of a post  (even with a hint that it was edited) then 99% of people will never see the original content.
That is more than enough for a "soft" censorship.
In the end I think we should focus more on educating people about this...

**Comment by erqan** [comment]
thanks to all for commenting...
it seems majority is against this feature, at least in this state. 
i am closing this request.. if anyone requires, it can be found at https://github.com/erqan/twister-core/tree/edit-post

**Comment by miguelfreitas** [comment]
Just some thoughts:

- I can hardly see how this could be called "censorship". Censorship, imho, involves a third party deciding over your content, preventing you from writing something or removing your writings. That's not the case: @erqan's proposal requires the owner to sign the drop/edit request. So only the content owner itself would be able to do that, not any govt.

- If i retract my own writing that would be "censorship"? Maybe "self-censorship" is a better description. Still, suppose you get a court order demanding you to delete a post, is it better to have such feature in twister to be able to comply the order or just tell the judge it is impossible/not implemented? That's an interesting consequence to consider.

- Previously, I have always been mentally blocked by the paradigm that a given piece that is already out in the network could not be removed. @erqan brings a different perspective: by propagating a new piece (which all nodes will do including old ones) it is possible to encode an instruction within requesting the peer to "drop/edit the piece number k". That's very elegant and clever.

- It is simply impossible to remove all the copies of the content that got published to the world. That's the very nature of digital information systems (copies are identical to the original). Twitter posts are not assured to be deleted either: people frequently do screenshots and copy-pastes to "prove" the deleted message existed at some point. I'd hardly believe Twitter itself removes the thing from their db. So the fact that a RT will preserve a copy of the old (unedited/non-deleted) message shouldn't leave anyone perplexed.

- Since it is easy to persist copies of the original content, it is insightful to discuss if such feature is worth implementing or if we are not providing a false sense of something that we can't strictly guarantee.

**Pull request closed without merging**
