### PR TITLE
enables readding a group key by `rescandirectmsgs` and `creategroup`

### LINKED ISSUE #381: can't join DMs group back with new wallet.dat
I've deleted my `wallet.dat` once in December 2015 as far as I remember, then created new one and imported my private key back. after that I did rescanning of direct messages. no groups.

inviting by someone else of a group doesn't work: I see all old messages in a group but can't send new ones:
> error encrypting to pubkey of destination user

if I'm leaving and trying to join back via the first section of twister-html's `#groupmessages+joingroup`:

> can't invite tasty to *randomID group — error encrypting to pubkey of group alias

the second section of that doesn't work because joining via `importprivkey` is impossible (yep, we try to do it this way for now: https://github.com/miguelfreitas/twister-html/blob/3d92f854101f05d18c0196022399e82230db773e/js/twister_directmsg.js#L369).

so I request  `importprivkeygroupdm` method or something and fixes for all related things.

### PR DESCRIPTION
**Pull request by erqan**
fix #381 partially...

### CODE REVIEW

**Comment by erqan** [comment]
and now a group key can be imported with ```creategroup``` (#381) @slr

**Comment by slr** [comment]
@erkan can you also bump twisterd version? I'm going to fix twister-html and it's good to know if `creategroup` is ready to be called.

**Comment by slr** [comment]
@erkan also it's need to handle error when entered private key for `creategroup` is invalid. I mean in RPC part.

**Comment by miguelfreitas** [comment]
looks good to me

**Comment by erqan** [comment]
0.9.38

**Comment by slr** [comment]
OK. I'll push some to twister-html on tomorrow's evening.

**Comment by slr** [comment]
>  I'll push some to twister-html on tomorrow's evening.

https://github.com/miguelfreitas/twister-html/commit/214ec3f3c7a9fade979abc135e6e85555d6f2dec

**Pull request merged**
