### PR TITLE
some cleaning of warnings...

### PR DESCRIPTION
**Pull request by erqan**

### CODE REVIEW

**Comment by miguelfreitas** [comment]
Thanks! That's a lot of work to fix all these warnings!

Please give me some time to review and test. I've just returned from vacations so I'm still working through my backlog...

**Comment by miguelfreitas** [comment]
Do we need to change compiler flags to support unique_ptr?
I'm getting tons of `error: 'unique_ptr' in namespace 'std' does not name a type`

That's with gcc 4.7.2 here. I've seen people saying that `-std=c++0x` is needed, so i wonder how it may have worked for you.

**Comment by erqan** [comment]
@miguelfreitas it's quite old.. please try with last commit..

**Comment by miguelfreitas** [comment]
Still not happy...

```
depbase=`echo libtorrent/src/alert_manager.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"twister\" -DPACKAGE_TARNAME=\"twister\" -DPACKAGE_VERSION=\"0.9.0\" -DPACKAGE_STRING=\"twister\ 0.9.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"twister\" -DVERSION=\"0.9.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD=1 -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_SYSTEM=/\*\*/ -DHAVE_BOOST_FILESYSTEM=/\*\*/ -DHAVE_BOOST_PROGRAM_OPTIONS=/\*\*/ -DHAVE_BOOST_THREAD=/\*\*/ -DHAVE_BOOST_CHRONO=/\*\*/ -DHAVE_BOOST_LOCALE=/\*\*/ -DHAVE_BOOST_REGEX=/\*\*/ -DDB_CXX_HEADER=\"db_cxx.h\" -DHAVE_GETHOSTBYNAME=1 -DHAVE_GETHOSTBYNAME_R=1 -DGETHOSTBYNAME_R_RETURNS_INT=1 -DHAVE_CLOCK_GETTIME=1 -DTORRENT_DEBUG=1 -DTORRENT_USE_OPENSSL=1 -DUSE_SSE2=1 -DENABLE_RSS=1 -DHAVE_LINUX_TYPES_H=1 -DHAVE_LINUX_FIEMAP_H=1 -DWITH_SHIPPED_GEOIP_H=1 -DBOOST_ASIO_HASH_MAP_BUCKETS=1021 -DBOOST_EXCEPTION_DISABLE=1 -DBOOST_ASIO_ENABLE_CANCELIO=1 -DBOOST_ASIO_DYN_LINK=1 -DTORRENT_BUILDING_SHARED=1 -I.  -ftemplate-depth-100 -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I./libtorrent/include -I./src -I./src/leveldb/include -I./src/leveldb/helpers  "-std=c++0x" -g -pthread -I/usr/include      -Wno-invalid-offsetof -g -O2 -fvisibility-inlines-hidden -DUSE_SSE2 -msse2  -mstackrealign -DENABLE_RSS  -MT libtorrent/src/alert_manager.o -MD -MP -MF $depbase.Tpo -c -o libtorrent/src/alert_manager.o libtorrent/src/alert_manager.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from /usr/include/boost/function/detail/maybe_include.hpp:18:0,
                 from /usr/include/boost/function/function1.hpp:11,
                 from ./libtorrent/include/libtorrent/alert_manager.hpp:40,
                 from libtorrent/src/alert_manager.cpp:34:
/usr/include/boost/function/function_template.hpp: In instantiation of âboost::function1<R, T1>::result_type boost::function1<R, T1>::operator()(T0) const [with R = void; T0 = std::unique_ptr<libtorrent::alert>; boost::function1<R, T1>::result_type = void]â:
libtorrent/src/alert_manager.cpp:88:54:   required from here
/usr/include/boost/function/function_template.hpp:760:71: error: use of deleted function âstd::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = libtorrent::alert; _Dp = std::default_delete<libtorrent::alert>; std::unique_ptr<_Tp, _Dp> = std::unique_ptr<libtorrent::alert>]â
In file included from /usr/include/c++/4.7/memory:86:0,
                 from ./libtorrent/include/libtorrent/alert.hpp:36,
                 from ./libtorrent/include/libtorrent/alert_manager.hpp:37,
                 from libtorrent/src/alert_manager.cpp:34:
/usr/include/c++/4.7/bits/unique_ptr.h:262:7: error: declared here
make: *** [libtorrent/src/alert_manager.o] Error 1
```

the "-std=c++0x" is there though.

**Comment by erqan** [comment]
the last commit should fix it.. *tested with gcc 4.6.2*

**Pull request closed without merging**
