### PR TITLE
added ports section

### PR DESCRIPTION
**Pull request by iShift**

### CODE REVIEW

**Comment by MauroMombelli** [comment]
@miguelfreitas why is this closed? what port should i open tomake twister work as best as possible?
28333 TCP + 29333 TCP+UDP? i can't find information anywhere!

**Comment by nitmir** [comment]
@MauroMombelli see #22

**Comment by miguelfreitas** [comment]
@MauroMombelli the listening port is now randomly choosen in latest twister version. If you want to open a fixed port, then pass port number you want using `-port N` parameter. Open `N` as TCP and `N+1000` as TCP+UDP.

**Comment by MauroMombelli** [comment]
can you please add this to the wiki or readme?

**Comment by miguelfreitas** [comment]
better yet: i'm considering adding it to the twister-html client, so user would know exactly which port is he actually using.

btw, anyone may contribute to wiki! :-)

**Pull request closed without merging**
