### PR TITLE
Open port 28333 in the proposed docker setup

### PR DESCRIPTION
**Pull request by black-puppydog**
Not sure why this was not enabled before.
Any good reasons not to?

### CODE REVIEW

**Comment by miguelfreitas** [comment]
What about 29333? It is the port used by the libtorrent part of twister.
It should improve sync'ing your posts (and people you follow).

**Comment by black-puppydog** [comment]
well that's something else entirely ;)
no serious, if that helps, why not also enable it?
Or was there a specific reason to not open those ports by default on docker?

**Comment by miguelfreitas** [comment]
I can't think of any reason either.
btw, can't you merge "-p 28332:28332 -p 28333:28333" as a single "-p 28332:28333" ?

**Comment by black-puppydog** [comment]
as I understand it, these numbers mean "map port 28332 of the docker virtual network interface to port 28332 of the host machine" and the same for port 28333. they are not ranges.

**Comment by casidiablo** [comment]
This might not be the place to ask for help but anyway... when I run twister on docker I can't seem to be able to access it via HTML. If I run, for instance, this command:

```sh
curl -v --user user:password localhost:28332
* Rebuilt URL to: localhost:28332/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 28332 (#0)
* Server auth using Basic with user 'user'
> GET / HTTP/1.1
> Authorization: Basic Y2FzaWRpYWJsbzpmdXMtc__TOGTFO
> User-Agent: curl/7.35.0
> Host: localhost:28332
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Date: Sun, 08 Mar 2015 20:23:07 +0000
< Connection: close
< Content-Length: 0
< Content-Type: application/json
* Server bitcoin-json-rpc/v0.9.28.0-unk-beta is not blacklisted
< Server: bitcoin-json-rpc/v0.9.28.0-unk-beta
<
* Closing connection 0
```

If I attach a bash session to the running container and try to do the same it works fine (the HTML is served):

```
docker exec -it $TWISTER_IMAGE bash
curl -v --user user:password localhost:28332
... everything works like a charm
```

Any ideas why this would happend?

**Comment by black-puppydog** [comment]
Sorry, completely forgot about this... but it should still make sense to open these ports.
E.g. arco asked about this in this conversation (not fully indexed yet)
https://twisterio.com/post/avatarx/721

**Pull request closed without merging**
