### PR TITLE
running twisterd on ios..

### PR DESCRIPTION
**Pull request by erqan**
- [x] building twisterd for ios..
- [ ] simple settings app for twister (i hope...)

### CODE REVIEW

**Comment by miguelfreitas** [comment]
great job, thanks!

**Comment by stman** [comment]
Hello Erqan.

I am an experienced iOS / Mac OS X developper, and I proposed a few month ago to Miguel to create a cool installer of Twister for Mac OS X with a Daemon Management Application perfectly integrated into Mac OS X (Icon in Task Bar, menu, etc... ) so that using Twisterd on Mac OS X doesn't require command line stuff to compile / configure everything.

As iOS and Mac OS X are the same , iOs being just a subsystem of OS X, and as Miguel is very busy, I would like to know if I could work directly with you, this will save time for Miguel, and as you managed to do 90% of the work needed to integrate it for Mac OS X with you version for iOS, I would love to contribute to your own work to port it on Mac OS X with a nice "Mac OS X style Manager app for the daemon", and maybe, why not, it's no big deal, a dedicated "App client" not "HTML based" but native in term of UI so that Mac Users that don't want to use their browser to connect to Twistterd, can have a "dedicated" super clean and beautifull "light client" on Mac OS X.

I proposed this work to Miguel several month ago, but I was too busy with many other projects I am working on. As now you have done the most difficult part, it will be easy for me to collaborate with you to do the job for Mac OS X.

I am looking forward to hearing from you,

Kind regards,

Frédéric.

a.k.a Stman

**Comment by rodneyrod** [comment]
@erqan and @stman best of luck to the both of you, it would be a real boon for Twister if these changes were implemented.

**Comment by stman** [comment]
I am really looking forward working with @erqan on this. It's effectively time for Twister to get as much support as possible.

**Comment by erqan** [comment]
@stman 
Hi Frédéric,
Thanks for your interest, but I don't work anymore on developing twister... :(

I hope you can find more suitable partner to work on this issue.

**Comment by stman** [comment]
@erqan No problem, I will work with those fixing stuff on Mac OS X version. @miguelfreitas

**Pull request merged**
